### ISSUE TITLE
Add PULL_REQUEST_TEMPLATE.md 

### ISSUE THREAD

**Issue by santoshvijapure** [InnovativeCoder/Innovative-Hacktober#129]
you can take reference of [https://github.com/stevemao/github-issue-templates](https://github.com/stevemao/github-issue-templates)

**Comment by bsoyka** [comment]
I’d like to take this one. 😄

**Comment by santoshvijapure** [comment]
sure.  
@bsoyka

**Comment by InnovativeCoder** [comment]
Thank you for this @bsoyka 
And thank you for managing the repo @santoshvijapure
