### ISSUE TITLE
Code is a bit messy

### ISSUE THREAD

**Issue by Sanjit1** [InnovativeCoder/Innovative-Hacktober#19]
There is code from people all over the place, and it would be nice to structure code into different directories from different projects, and thus there will never be any pull request merging conflicts because many people will have the same name(for example main.py or index.html) after more pull requests come in. It would also be good if the new contributors learn how to add readmes with tools such as stackedit, and have their individual readmes in their individual directories. If I have time in school tommorow I might open a huge pull request where I plan to make the following changes:
- Add a contributing.md
- Look at all merged pull requests and make individual directories for each of those pull requests, so that all projects are arranged and in a proper page. 
- Review the new pull requests and ask them to move their code into a directory inside their fork of Innovative-October.

It would be nice if you approve that I can continue with the pull request so that I do not start working without any cause

![badge](https://img.shields.io/badge/Best%20regards-Sanjit-accff2?style=for-the-badge)

**Comment by santoshvijapure** [comment]
hello, @Sanjit1 Thank you for showing interest in our community.
you are right, there are multiple possibilities where merge conflicts can happen.

can you please open pull request will all your changes.
:)

**Comment by InnovativeCoder** [comment]
@santoshvijapure I have had a chat with him on Instagram, he is cleaning the code and will open the PR by morning.

**Comment by santoshvijapure** [comment]
cool  : } @InnovativeCoder

**Comment by Sanjit1** [comment]
Well, it seems like you guys are covered. Do you still need help?
If yes then where?

**Comment by InnovativeCoder** [comment]
Nope, now done.
